#+TITLE: Mind games

Mind games are a difficult topic to discuss. Here I'll just give a simple summary of how they are established. 

Many players can overestimate an opponent’s ability to play mind games by simply not understanding the situations they find themselves in or testing their opponent’s ability to fight against all of the options. Only once both players truly understand all of the options open to them can real mind games begin. Here, knowledge is an absolute prerequisite.

#+begin_quote
It is only about the opponent. 
How careful is the opponent? How risky is the opponent?  --- Inoue (Kazunoko)
#+end_quote

Most mind games are based on a natural imbalance created by different characters having different strengths. Typically one character will have advantage over another in the neutral or when their opponent is knocked down. 

For example, in a neutral situation, King is able to initiate moves which you must react to, and also has the option to not press anything at all or do something completely different. In this way King has an advantage. Your character, mirror matches excluded, will need to approach. This is not an RPS scenario because King has the advantage due to venom strikes and how moves interact. She doesn't need to use her normals! She can do anything, but you cannot. You must think about several options. In this way we consider it as "King has the initiative in neutral" as she decides how you engage with each other at range and you must work around it with your character's specific options.

The distribution between who has the advantage and the disadvantage entirely depends on matchup. You must understand your character’s options and the behaviours of your opponent before you can assess how much risk they are taking and being able to respond accordingly.

Some elementary principles on what you should look for are the following:

- How is the opponent maneuvering?
- Does the opponent tend to take greater risks?
- Does the opponent tend to minimise risks?
- What moves, and how much, does this opponent rely on?

It is all about the opponent and the opponent at higher levels will be thinking the same thing. Therefore, mind games emerge in a constant interaction between two players’

- Level of knowledge
- Decision making from a risk-reward viewpoint
- Execution.

Hence, mind games must always keep to a predetermined interaction between two characters’

- Anti-air options
- Moves within the three-structure
- Offensive/defensive options.

Whether your knowledge comes from playing matches or training mode, the absolutely most vital thing you must do is put in the legwork to know all that you can beforehand.
